name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: '3.13.0'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: helm plugin install https://github.com/helm-unittest/helm-unittest.git

      - name: Lint Helm chart
        run: |
          helm lint pre-porter

      - name: Run Helm unit tests
        run: |
          helm unittest pre-porter

      - name: Test Helm template rendering
        run: |
          # Test with default values
          helm template test-release pre-porter > /dev/null
          
          echo "✅ All template rendering tests passed"
